title: "MODIS-LAI"
description: >
  A prototype test for the LEAP Data Library refactor
recipes:
  - id: "MODIS-LAI"
    object: "recipe:MODIS-LAI"
provenance:
  providers:
    - name: "NASA MODIS"
      description: "Level-1 and Atmosphere Archive & Distribution System
Distributed Active Archive Center"
      roles:
        - host
        url: https://ladsweb.modaps.eosdis.nasa.gov/archive/allData/6/MOD15A2GFS/
        - licensor
  license: "NASA Open Data- Creative Commons Zero (CC0)"
maintainers:
  - name: "Raphael Hagen"
    github: norlandrhagen
  - name: "Mitra Cattry"
    github: mitraA90
