title: "CanopyHeights-GLAD"
description: "High-resolution global canopy height dataset derived from Sentinel-2 imagery for land surface and forest structure analysis. Based on ETH Global Sentinel-2 10m Canopy Height (2023) and GLAD methodologies."

recipes:
  - id: "CanopyHeights-GLAD"
    object: "recipe:CanopyHeights-GLAD"

provenance:
  providers:
    - name: "ETH Global"
      description: "ETH Zurich's global canopy height dataset derived from Sentinel-2 satellite imagery"
      roles:
        - data provider
        - research institution
      url: "https://doi.org/10.3929/ethz-b-000609802"

    - name: "GLAD - Global Land Analysis & Discovery Group"
      description: "Global Land Analysis & Discovery (GLAD) group at the University of Maryland, specializing in forest monitoring and remote sensing."
      roles:
        - data provider
        - research institution
      url: "https://glad.umd.edu"

  license: "Creative Commons Attribution 4.0 (CC BY 4.0)"

acknowledgements: >
  The Canopy Heights dataset is based on the **ETH Global Sentinel-2 10m Canopy Height dataset (2020)** and incorporates methodologies from the **Global Land Analysis & Discovery (GLAD) group**. We acknowledge **ETH Zurich** for providing the Sentinel-2-derived canopy height data, accessible at https://gee-community-catalog.org/projects/canopy/. This dataset has been validated using various in-situ and airborne LiDAR measurements. We also thank the NASA GEDI mission, OpenTopography, and Forest Inventory and Analysis (FIA) programs for providing reference datasets that contributed to canopy height validation. 

citation:
  - authors: "Potapov, P., Hansen, M.C., Pickens, A., Hernandez-Serna, A., Tyukavina, A., Turubanova, S., Zalles, V., Li, X., Khan, A., Stolle, F., Harris, N., Song, X.-P., Baggett, A., Kommareddy, I., Kommareddy, A."
    year: 2022
    title: "The global 2000-2020 land cover and land use change dataset derived from the Landsat archive: first results"
    journal: "Frontiers in Remote Sensing"
    volume: 3
    pages: 856903
    doi: "10.3389/frsen.2022.856903"
    
  - authors: "Lang, N., Schleppi, P., Durrieu, S., Schardt, M., Wegmann, M."
    year: 2023
    title: "Global High-Resolution Canopy Height Estimation Using Sentinel-2 and Machine Learning"
    journal: "Remote Sensing"
    volume: 15
    pages: 3102
    doi: "10.3390/rs15123102"

  - authors: "Lang, Nico, Walter Jetz, Konrad Schindler, and Jan Dirk Wegner."
    year: 2022
    title: "A high-resolution canopy height model of the Earth."
    journal: "Nature Communications"
    doi: "arXiv preprint arXiv:2204.08322"
contact:
  email: "jandirk.wegner@uzh.ch"

maintainers:
  - name: "Mitra Cattry"
    github: "mitraA90"
  - name: "Raphael Hagen"
    github: "norlandrhagen"
