title: "CanopyHeights-GLAD"
description: "High-resolution global canopy height dataset derived from Sentinel-2 imagery for land surface and forest structure analysis. Based on ETH Global Sentinel-2 10m Canopy Height (2023) and GLAD methodologies."

recipes:
  - id: "CanopyHeights-GLAD"
    object: "recipe:CanopyHeights-GLAD"

provenance:
  providers:
    - name: "ETH Global"
      description: "ETH Zurich's global canopy height dataset derived from Sentinel-2 satellite imagery"
      roles:
        - data provider
        - research institution
      url: "https://doi.org/10.3929/ethz-b-000609802"

    - name: "GLAD - Global Land Analysis & Discovery Group"
      description: "Global Land Analysis & Discovery (GLAD) group at the University of Maryland, specializing in forest monitoring and remote sensing."
      roles:
        - data provider
        - research institution
      url: "https://glad.umd.edu"

  license: "Creative Commons Attribution 4.0 (CC BY 4.0)"

citation:
  - authors: "Potapov, P., Hansen, M.C., Pickens, A., Hernandez-Serna, A., Tyukavina, A., Turubanova, S., Zalles, V., Li, X., Khan, A., Stolle, F., Harris, N., Song, X.-P., Baggett, A., Kommareddy, I., Kommareddy, A."
    year: 2022
    title: "The global 2000-2020 land cover and land use change dataset derived from the Landsat archive: first results"
    journal: "Frontiers in Remote Sensing"
    volume: 3
    pages: 856903
    doi: "10.3389/frsen.2022.856903"

  - authors: "Lang, Nico, Walter Jetz, Konrad Schindler, and Jan Dirk Wegner."
    year: 2022
    title: "A high-resolution canopy height model of the Earth."
    journal: "Nature Ecology & Evolution"
    doi: "arXiv preprint arXiv:2204.08322"
contact:
  email: "jandirk.wegner@uzh.ch"
  email: "ma4451@columbia.edu"

maintainers:
  - name: "Mitra Cattry"
    github: "mitraA90"
